WoolfCMH = function(x,alpha=0.05) {
       x <- x + 1 / 2
       k <- dim(x)[3]
#      Odds Ratio
       or <- apply(x, 3, function(x) (x[1,1]*x[2,2])/(x[1,2]*x[2,1]))
       w <-  apply(x, 3, function(x) 1 / sum(1 / x))
       log.orW <- sum(w*log(or))/sum(w)
       or.wCI <- exp(log.orW + c(-1,1)*qnorm(1-alpha/2)*sqrt(1/sum(w)))
       chisq.OR<-sum(w * (log(or) - weighted.mean(log(or), w)) ^ 2)
       p.or<- 1- pchisq(chisq.OR,k-1)
#      Woolf Relative Risk
       x <- x - 1/2
       rr <- apply(x,3,function(x) (x[1,1]*(x[2,1]+x[2,2])) / (x[2,1]*(x[1,1]+x[1,2])))
       w <-apply(x,3,function(x) 1 / (x[1,2]/(x[1,1]*(x[1,1]+x[1,2])) + x[2,2]/(x[2,1]*(x[2,1]+x[2,2]))))
       chisq.RR<-sum(w * (log(rr) - weighted.mean(log(rr), w)) ^ 2)
       p.rr<- 1- pchisq(chisq.RR,k-1)
       log.rrW<-sum(w*log(rr))/sum(w)
       rr.wCI <- exp(log.rrW + c(-1,1)*qnorm(1-alpha/2)*sqrt(1/sum(w)))
#      Woolf Excess Risk
       er <- apply(x,3,function(x) x[1,1]/(x[1,1]+x[1,2]) - x[2,1]/(x[2,1]+x[2,2]))
       w <- apply(x,3,function(x) 1 / (x[1,1]*x[1,2]/(x[1,1]+x[1,2])^3 + x[2,1]*x[2,2]/(x[2,1]+x[2,2])^3))
       chisq.ER<-sum(w*(er - weighted.mean(er,w))^2)
       p.er<- 1- pchisq(chisq.ER,k-1)
       er.W <- sum(w*er)/sum(w)
       er.wCI <- er.W + c(-1,1)*qnorm(1 - alpha/2)*sqrt(1/sum(w))
       ##
       ##
       # CMH Odds Ratio
       MH<-mantelhaen.test(x)
       # CMH Relative Risk
       num<-apply(x,3,function(x) (x[1,1]*(x[2,1]+x[2,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])))
       denom<-apply(x,3,function(x) (x[2,1]*(x[1,1]+x[1,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])))
       rr.mh<-sum(num)/sum(denom)
       num.var<-apply(x,3,function(x) ((x[1,1]+x[1,2])*(x[2,1]+x[2,2])*(x[1,1]+x[2,1]) - x[1,1]*x[2,1]*(x[1,1]+x[1,2]+x[2,1]+x[2,2]))/(x[1,1]+x[1,2]+x[2,1]+x[2,2])^2)
       denom1.var<-apply(x,3,function(x) (x[1,1]*(x[2,1]+x[2,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])))
       denom2.var<-apply(x,3,function(x) (x[2,1]*(x[1,1]+x[1,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])))
       se.logrr<-sqrt( sum(num.var)/(sum(denom1.var)*sum(denom2.var)))
       rrMH.ci<-exp(log(rr.mh) + c(-1,1)*qnorm(1-alpha/2)*se.logrr)
       # CMH Excess Risk
       num.er<-apply(x,3,function(x) (x[1,1]*(x[2,1]+x[2,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])) - (x[2,1]*(x[1,1]+x[1,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2])))
       denom.er<-apply(x,3,function(x) (x[1,1]+x[1,2])*(x[2,1]+x[2,2])/(x[1,1]+x[1,2]+x[2,1]+x[2,2]))
       er.MH<-sum(num.er)/(sum(denom.er))
       num.var<-apply(x,3,function(x) ( x[1,1]*x[1,2]*(x[2,1]+x[2,2])^3 + x[2,1]*x[2,2]*(x[1,1]+x[1,2])^3)/((x[1,1]+x[1,2])*(x[2,1]+x[2,2])*(x[1,1]+x[1,2]+x[2,1]+x[2,2])^2))
       se.er<-sqrt(sum(num.var)/(sum(denom.er)^2))
       erMH.ci<-er.MH + c(-1,1)*qnorm(1-alpha/2)*se.er
       cat("\n")
       cat("Woolf's Method for Estimating OR, RR, and ER Across Strata\n")
       cat("=========================================================\n")
       #cat(paste("OR p-value =",round(p,3)))
       cat(paste("Woolf OR Chi-squared=",round(chisq.OR,3),"OR p-value =",round(p.or,3)))
       cat("\n")
       cat(paste("Woolf OR =",round(exp(log.orW),3)))
       cat("\n")
       cat(paste("Odds Ratio CI =",round(or.wCI,3)))
       cat("\n")
       cat(paste("Woolf RR Chi-squared=",round(chisq.RR,3),"RR p-value =",round(p.rr,3)))
       cat("\n")
       cat(paste("Woolf RR =",round(exp(log.rrW),3)))
       cat("\n")
       cat(paste("Relative Risk CI =",round(rr.wCI,3)))
       cat("\n")
        cat(paste("Woolf ER Chi-squared=",round(chisq.ER,3),"ER p-value =",round(p.er,3)))
       cat("\n")
       cat(paste("Woolf ER =",round(er.W,4)))
       cat("\n")
       cat(paste("Excess Risk CI =",round(er.wCI,4)))
       cat("\n")
        cat("=========================================================\n")
       cat("CMH Method for Estimating OR, RR, and ER Across Strata\n")
       cat("=========================================================\n")
        cat(paste("CMH OR =",round(MH$estimate,3)))
       cat("\n")
       cat(paste("Odds Ratio CI =",round(MH$conf.int,3)))
       cat("\n")
       cat(paste("CMH RR =",round(rr.mh,3)))
       cat("\n")
       cat(paste("Relative Risk CI =",round(rrMH.ci,3)))
       cat("\n")
       cat(paste("CMH ER =",round(er.MH,4)))
       cat("\n")
      cat(paste("Excess Risk CI =",round(erMH.ci,4)))
      cat("\n")
     }
